import {
  Brain, BarChart3, Monitor, Mic, Leaf, Users,
  TrendingUp, Wifi, MapPin, Play, Calendar,
  GraduationCap, Award, Badge
} from "lucide-react";

export const CATEGORIES = [
  { id: "all",        label: "All",         icon: "Globe" },
  { id: "sales",      label: "Sales",       icon: "BarChart3" },
  { id: "tech",       label: "Tech",        icon: "Monitor" },
  { id: "leadership", label: "Leadership",  icon: "Users" },
  { id: "softskills", label: "Soft Skills", icon: "Mic" },
  { id: "wellness",   label: "Wellness",    icon: "Leaf" },
  { id: "ai",         label: "AI & ML",     icon: "Brain" },
];

export const CAT_COLORS = {
  sales:      { bg: "bg-amber-100",   text: "text-amber-700",   border: "border-amber-200",   accent: "from-amber-500 to-orange-500",  gradient: "from-amber-600 to-orange-600",  pill: "#F59E0B" },
  tech:       { bg: "bg-cyan-100",    text: "text-cyan-700",    border: "border-cyan-200",    accent: "from-cyan-500 to-blue-600",     gradient: "from-cyan-600 to-blue-700",     pill: "#0891B2" },
  leadership: { bg: "bg-violet-100",  text: "text-violet-700",  border: "border-violet-200",  accent: "from-violet-500 to-purple-700", gradient: "from-violet-600 to-purple-700", pill: "#7C3AED" },
  softskills: { bg: "bg-pink-100",    text: "text-pink-700",    border: "border-pink-200",    accent: "from-pink-500 to-rose-600",     gradient: "from-pink-600 to-rose-600",     pill: "#EC4899" },
  wellness:   { bg: "bg-emerald-100", text: "text-emerald-700", border: "border-emerald-200", accent: "from-emerald-500 to-teal-600",  gradient: "from-emerald-600 to-teal-700",  pill: "#10B981" },
  ai:         { bg: "bg-orange-100",  text: "text-orange-700",  border: "border-orange-200",  accent: "from-orange-500 to-red-500",    gradient: "from-orange-600 to-red-600",    pill: "#F97316" },
};

export const WORKSHOPS = [
  {
    id: 1, category: "sales", isLive: true, featured: true,
    slug: "advanced-b2b-sales-mastery",
    title: "Advanced B2B Sales Mastery",
    shortDesc: "Master enterprise deal-closing, negotiation tactics, and consultative selling frameworks.",
    fullDesc: "This intensive workshop takes you deep into the world of enterprise B2B selling. You will learn how to map complex stakeholder landscapes, build champions inside client organisations, and close high-value deals using proven consultative frameworks. Topics include multi-threaded pipeline management, SPIN selling, MEDDIC qualification, pricing negotiations, and post-sale expansion strategies. Every module is backed by real Fortune 500 case studies and live role-play exercises.",
    price: { original: 24999, discounted: 14999, emi: "1,250", includes: ["Certificate", "Workbook", "Lifetime Access", "1-on-1 Mentoring"] },
    duration: "3 Days", seats: 42, rating: "4.9", reviews: "1.2k",
    dateRange: "25 - 27 May 2025", timeSlot: "10:00 AM - 01:00 PM", enrolled: 85,
    tags: ["B2B", "Negotiation", "Pipeline"],
    coverImg: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=700&h=420&fit=crop",
    photos: [
      { src: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=260&fit=crop", label: "Live webinar" },
      { src: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=400&h=260&fit=crop", label: "Offline session" },
      { src: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=400&h=260&fit=crop", label: "Team workshop" },
      { src: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=260&fit=crop", label: "Mentoring" },
    ],
    trainer: {
      name: "Amit Kumar", role: "Sales Director, Fortune 500", exp: "12+ Yrs",
      students: "8,400+", initials: "AK",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=faces",
      certifications: ["Sandler Certified", "HubSpot Certified"],
      classTypes: [
        { type: "Live Online", count: "48 sessions", iconName: "Wifi",     colorClass: "text-blue-600",    bgClass: "bg-blue-50",    borderClass: "border-blue-200"    },
        { type: "Offline",     count: "24 sessions", iconName: "MapPin",   colorClass: "text-emerald-600", bgClass: "bg-emerald-50", borderClass: "border-emerald-200" },
        { type: "Recorded",    count: "120+ hrs",    iconName: "Play",     colorClass: "text-violet-600",  bgClass: "bg-violet-50",  borderClass: "border-violet-200"  },
        { type: "Workshop",    count: "12 batches",  iconName: "Calendar", colorClass: "text-amber-600",   bgClass: "bg-amber-50",   borderClass: "border-amber-200"   },
      ],
    },
  },
  {
    id: 2, category: "tech", isLive: false, featured: false,
    slug: "full-stack-web-dev-bootcamp",
    title: "Full-Stack Web Dev Bootcamp",
    shortDesc: "Hands-on intensive covering React, Node.js, cloud deployment and real capstone projects.",
    fullDesc: "A comprehensive deep-dive into modern full-stack engineering. You will build three production-grade capstone apps from scratch, covering React 18, Next.js, Node.js, PostgreSQL, REST & GraphQL APIs, Docker, and AWS deployment pipelines. The bootcamp follows a learn-by-doing philosophy — every concept is immediately applied in code. You will finish with a portfolio-ready GitHub profile and personalised job-readiness coaching from a senior Google engineer.",
    price: { original: 39999, discounted: 24999, emi: "2,083", includes: ["Certificate", "Source Code", "Cloud Credits", "Job Assist"] },
    duration: "5 Days", seats: 18, rating: "4.8", reviews: "980",
    dateRange: "01 - 05 Jun 2025", timeSlot: "09:00 AM - 12:00 PM", enrolled: 60,
    tags: ["React", "Node.js", "AWS"],
    coverImg: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=700&h=420&fit=crop",
    photos: [
      { src: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400&h=260&fit=crop", label: "Coding live" },
      { src: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=400&h=260&fit=crop", label: "Group lab" },
      { src: "https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=400&h=260&fit=crop", label: "Code review" },
      { src: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=260&fit=crop", label: "Demo day" },
    ],
    trainer: {
      name: "Sara Reddy", role: "Senior Engineer, Google", exp: "9+ Yrs",
      students: "6,200+", initials: "SR",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=faces",
      certifications: ["Google Cloud Certified", "AWS Associate"],
      classTypes: [
        { type: "Live Online", count: "60 sessions", iconName: "Wifi",          colorClass: "text-blue-600",    bgClass: "bg-blue-50",    borderClass: "border-blue-200"    },
        { type: "Offline",     count: "18 sessions", iconName: "MapPin",        colorClass: "text-emerald-600", bgClass: "bg-emerald-50", borderClass: "border-emerald-200" },
        { type: "Recorded",    count: "200+ hrs",    iconName: "Play",          colorClass: "text-violet-600",  bgClass: "bg-violet-50",  borderClass: "border-violet-200"  },
        { type: "Bootcamp",    count: "8 batches",   iconName: "GraduationCap", colorClass: "text-cyan-600",    bgClass: "bg-cyan-50",    borderClass: "border-cyan-200"    },
      ],
    },
  },
  {
    id: 3, category: "leadership", isLive: false, featured: true,
    slug: "executive-leadership-team-building",
    title: "Executive Leadership & Team Building",
    shortDesc: "Transform your leadership style with frameworks used by top CEOs worldwide.",
    fullDesc: "Designed for mid-to-senior leaders who want to elevate their impact, this workshop blends adaptive leadership theory with hands-on practice. You will work through real-world case studies from McKinsey, IIM research, and global CEO playbooks. Core modules cover psychological safety, OKR goal-setting, navigating conflict, giving high-quality feedback, building high-performance culture, and executive presence. Includes a 360-degree feedback assessment and a 30-day implementation plan you will leave with on day two.",
    price: { original: 19999, discounted: 11999, emi: "1,000", includes: ["Certificate", "Toolkit", "Peer Network", "Coaching"] },
    duration: "2 Days", seats: 30, rating: "5.0", reviews: "650",
    dateRange: "08 - 09 Jun 2025", timeSlot: "11:00 AM - 02:00 PM", enrolled: 45,
    tags: ["Leadership", "OKRs", "Culture"],
    coverImg: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=700&h=420&fit=crop",
    photos: [
      { src: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=260&fit=crop", label: "Live session" },
      { src: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=260&fit=crop", label: "Offline class" },
      { src: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=400&h=260&fit=crop", label: "Team exercise" },
      { src: "https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?w=400&h=260&fit=crop", label: "Group coaching" },
    ],
    trainer: {
      name: "Maya Joshi", role: "Executive Coach, IIM Faculty", exp: "15+ Yrs",
      students: "11,000+", initials: "MJ",
      avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop&crop=faces",
      certifications: ["ICF PCC Certified", "Marshall Goldsmith"],
      classTypes: [
        { type: "Live Online", count: "36 sessions", iconName: "Wifi",   colorClass: "text-blue-600",    bgClass: "bg-blue-50",    borderClass: "border-blue-200"    },
        { type: "Offline",     count: "20 sessions", iconName: "MapPin", colorClass: "text-emerald-600", bgClass: "bg-emerald-50", borderClass: "border-emerald-200" },
        { type: "Recorded",    count: "80+ hrs",     iconName: "Play",   colorClass: "text-violet-600",  bgClass: "bg-violet-50",  borderClass: "border-violet-200"  },
        { type: "Coaching",    count: "15 batches",  iconName: "Award",  colorClass: "text-amber-600",   bgClass: "bg-amber-50",   borderClass: "border-amber-200"   },
      ],
    },
  },
  {
    id: 4, category: "ai", isLive: true, featured: true,
    slug: "ai-machine-learning-for-business",
    title: "AI & Machine Learning for Business",
    shortDesc: "Implement AI tools in your business — automate, predict, optimise with no-code platforms.",
    fullDesc: "No PhD required. This workshop is purpose-built for business leaders, product managers, and entrepreneurs who want to harness AI without writing complex code. You will explore prompt engineering, GPT-powered automations, no-code ML platforms (DataRobot, Obviously.AI), computer vision use cases, and AI-driven analytics dashboards. By the end you will have deployed at least two working AI automations for your own business context — not toy demos, but real tools.",
    price: { original: 29999, discounted: 17999, emi: "1,500", includes: ["Certificate", "AI Tool Suite", "Templates", "Community"] },
    duration: "2 Days", seats: 25, rating: "4.9", reviews: "870",
    dateRange: "15 - 16 Jun 2025", timeSlot: "10:00 AM - 01:00 PM", enrolled: 72,
    tags: ["Prompt Eng.", "No-Code ML", "Automation"],
    coverImg: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=700&h=420&fit=crop",
    photos: [
      { src: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&h=260&fit=crop", label: "AI webinar" },
      { src: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400&h=260&fit=crop", label: "Offline lab" },
      { src: "https://images.unsplash.com/photo-1655720406002-3b1c6e6c24fc?w=400&h=260&fit=crop", label: "Model training" },
      { src: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=400&h=260&fit=crop", label: "Demo session" },
    ],
    trainer: {
      name: "Ravi Nair", role: "AI Researcher, IIT Bombay", exp: "10+ Yrs",
      students: "5,800+", initials: "RN",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=faces",
      certifications: ["TensorFlow Developer", "DeepLearning.AI"],
      classTypes: [
        { type: "Live Online", count: "52 sessions", iconName: "Wifi",   colorClass: "text-blue-600",    bgClass: "bg-blue-50",    borderClass: "border-blue-200"    },
        { type: "Offline",     count: "16 sessions", iconName: "MapPin", colorClass: "text-emerald-600", bgClass: "bg-emerald-50", borderClass: "border-emerald-200" },
        { type: "Recorded",    count: "150+ hrs",    iconName: "Play",   colorClass: "text-violet-600",  bgClass: "bg-violet-50",  borderClass: "border-violet-200"  },
        { type: "AI Lab",      count: "10 batches",  iconName: "Brain",  colorClass: "text-orange-600",  bgClass: "bg-orange-50",  borderClass: "border-orange-200"  },
      ],
    },
  },
  {
    id: 5, category: "softskills", isLive: false, featured: false,
    slug: "public-speaking-communication",
    title: "Public Speaking & Communication",
    shortDesc: "Build vocal presence and storytelling ability to command any stage or boardroom.",
    fullDesc: "This is the most practically intense communication workshop available in India. You will be on your feet speaking from day one. Modules cover voice modulation, eliminating filler words, crafting a compelling narrative arc, handling tough Q&A sessions, presenting data visually, and owning the room with confident body language. Every participant receives a personal video recording of their before-and-after presentations, plus a private one-on-one feedback call with Priya post-workshop.",
    price: { original: 12999, discounted: 7499, emi: "625", includes: ["Certificate", "Recordings", "Feedback", "Resources"] },
    duration: "1 Day", seats: 50, rating: "4.7", reviews: "540",
    dateRange: "22 Jun 2025", timeSlot: "09:00 AM - 05:00 PM", enrolled: 38,
    tags: ["Public Speaking", "Storytelling", "Presence"],
    coverImg: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=700&h=420&fit=crop",
    photos: [
      { src: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=400&h=260&fit=crop", label: "Online talk" },
      { src: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=400&h=260&fit=crop", label: "Stage session" },
      { src: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=260&fit=crop", label: "Conference" },
      { src: "https://images.unsplash.com/photo-1560523159-4a9692d222ef?w=400&h=260&fit=crop", label: "Live coaching" },
    ],
    trainer: {
      name: "Priya Das", role: "TED Speaker & Coach", exp: "8+ Yrs",
      students: "14,500+", initials: "PD",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=faces",
      certifications: ["Toastmasters DTM", "NLP Practitioner"],
      classTypes: [
        { type: "Live Online",    count: "40 sessions", iconName: "Wifi",  colorClass: "text-blue-600",    bgClass: "bg-blue-50",    borderClass: "border-blue-200"    },
        { type: "Offline",        count: "22 sessions", iconName: "MapPin",colorClass: "text-emerald-600", bgClass: "bg-emerald-50", borderClass: "border-emerald-200" },
        { type: "Recorded",       count: "60+ hrs",     iconName: "Play",  colorClass: "text-violet-600",  bgClass: "bg-violet-50",  borderClass: "border-violet-200"  },
        { type: "Stage Practice", count: "20 batches",  iconName: "Mic",   colorClass: "text-pink-600",    bgClass: "bg-pink-50",    borderClass: "border-pink-200"    },
      ],
    },
  },
  {
    id: 6, category: "wellness", isLive: false, featured: false,
    slug: "workplace-mindfulness-stress-management",
    title: "Workplace Mindfulness & Stress Management",
    shortDesc: "Evidence-based mindfulness to sharpen focus and build emotional resilience at work.",
    fullDesc: "Burnout is an epidemic. This workshop gives you a science-backed toolkit to reclaim your mental bandwidth and sustain peak performance without sacrificing wellbeing. Drawing from MBSR (Mindfulness-Based Stress Reduction), cognitive behavioural therapy principles, and ancient breathwork practices, Ananya guides you through techniques you can embed into your working day in under 10 minutes. Corporate teams report a 40% drop in reported stress levels within 4 weeks of applying these methods.",
    price: { original: 9999, discounted: 5999, emi: "500", includes: ["Certificate", "App Access", "Check-ins", "Journal"] },
    duration: "1 Day", seats: 60, rating: "4.8", reviews: "430",
    dateRange: "29 Jun 2025", timeSlot: "10:00 AM - 04:00 PM", enrolled: 55,
    tags: ["MBSR", "Breathwork", "Resilience"],
    coverImg: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=700&h=420&fit=crop",
    photos: [
      { src: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=260&fit=crop", label: "Online session" },
      { src: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400&h=260&fit=crop", label: "Yoga class" },
      { src: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&h=260&fit=crop", label: "Breathwork" },
      { src: "https://images.unsplash.com/photo-1491555103944-7c647fd857e6?w=400&h=260&fit=crop", label: "Group retreat" },
    ],
    trainer: {
      name: "Ananya Shah", role: "Certified Mindfulness Coach", exp: "11+ Yrs",
      students: "9,300+", initials: "AS",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=faces",
      certifications: ["MBSR Certified", "Yoga Alliance 500H"],
      classTypes: [
        { type: "Live Online", count: "30 sessions", iconName: "Wifi",   colorClass: "text-blue-600",    bgClass: "bg-blue-50",    borderClass: "border-blue-200"    },
        { type: "Offline",     count: "15 sessions", iconName: "MapPin", colorClass: "text-emerald-600", bgClass: "bg-emerald-50", borderClass: "border-emerald-200" },
        { type: "Recorded",    count: "45+ hrs",     iconName: "Play",   colorClass: "text-violet-600",  bgClass: "bg-violet-50",  borderClass: "border-violet-200"  },
        { type: "Retreat",     count: "6 batches",   iconName: "Leaf",   colorClass: "text-emerald-600", bgClass: "bg-emerald-50", borderClass: "border-emerald-200" },
      ],
    },
  },
  {
    id: 7, category: "tech", isLive: false, featured: false,
    slug: "data-science-python-analytics",
    title: "Data Science & Python Analytics",
    shortDesc: "From raw data to actionable insights — master pandas, visualisation and predictive models.",
    fullDesc: "A practical, project-led data science workshop. You will work with real datasets, applying Python (pandas, NumPy, matplotlib, seaborn), build regression and classification models with scikit-learn, and create interactive dashboards with Plotly and Streamlit. Ideal for analysts, product managers, and engineers wanting to become data-fluent. You leave with 3 complete data projects on GitHub and a Kaggle-ready skillset.",
    price: { original: 18999, discounted: 10999, emi: "916", includes: ["Certificate", "Datasets", "Notebooks", "Career Guide"] },
    duration: "3 Days", seats: 35, rating: "4.8", reviews: "320",
    dateRange: "05 - 07 Jul 2025", timeSlot: "10:00 AM - 01:00 PM", enrolled: 48,
    tags: ["Python", "Pandas", "ML Models"],
    coverImg: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=700&h=420&fit=crop",
    photos: [
      { src: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=260&fit=crop", label: "Data lab" },
      { src: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=400&h=260&fit=crop", label: "Workshop" },
      { src: "https://images.unsplash.com/photo-1543286386-713bdd548da4?w=400&h=260&fit=crop", label: "Dashboard" },
      { src: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=260&fit=crop", label: "Analytics" },
    ],
    trainer: {
      name: "Karan Malhotra", role: "Data Lead, Microsoft India", exp: "8+ Yrs",
      students: "4,100+", initials: "KM",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=faces",
      certifications: ["Azure Data Scientist", "Kaggle Expert"],
      classTypes: [
        { type: "Live Online", count: "40 sessions", iconName: "Wifi",      colorClass: "text-blue-600",    bgClass: "bg-blue-50",    borderClass: "border-blue-200"    },
        { type: "Offline",     count: "12 sessions", iconName: "MapPin",    colorClass: "text-emerald-600", bgClass: "bg-emerald-50", borderClass: "border-emerald-200" },
        { type: "Recorded",    count: "100+ hrs",    iconName: "Play",      colorClass: "text-violet-600",  bgClass: "bg-violet-50",  borderClass: "border-violet-200"  },
        { type: "Data Lab",    count: "8 batches",   iconName: "BarChart3", colorClass: "text-cyan-600",    bgClass: "bg-cyan-50",    borderClass: "border-cyan-200"    },
      ],
    },
  },
  {
    id: 8, category: "leadership", isLive: false, featured: false,
    slug: "strategic-thinking-decision-making",
    title: "Strategic Thinking & Decision Making",
    shortDesc: "Sharpen your strategic mind with mental models, frameworks and case-study simulations.",
    fullDesc: "This workshop equips you with the cognitive toolkit to think clearly under pressure and make decisions that hold. You will study and apply 20+ mental models — first principles, inversion, second-order thinking, Bayesian updating — through structured case simulations drawn from global companies and Indian startups. Ideal for founders, senior managers, and consultants who need to level up their strategic acuity quickly.",
    price: { original: 16999, discounted: 9999, emi: "833", includes: ["Certificate", "Mental Models Deck", "Cases", "Peer Forum"] },
    duration: "2 Days", seats: 28, rating: "4.9", reviews: "280",
    dateRange: "12 - 13 Jul 2025", timeSlot: "09:00 AM - 05:00 PM", enrolled: 32,
    tags: ["Strategy", "Mental Models", "Decision Making"],
    coverImg: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=700&h=420&fit=crop",
    photos: [
      { src: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=260&fit=crop", label: "Strategy session" },
      { src: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=400&h=260&fit=crop", label: "Whiteboard" },
      { src: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=400&h=260&fit=crop", label: "Case study" },
      { src: "https://images.unsplash.com/photo-1552581234-26160f608093?w=400&h=260&fit=crop", label: "Group work" },
    ],
    trainer: {
      name: "Vikram Bose", role: "Strategy Consultant, Ex-BCG", exp: "13+ Yrs",
      students: "3,700+", initials: "VB",
      avatar: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=200&h=200&fit=crop&crop=faces",
      certifications: ["Wharton Strategy", "HBS Online"],
      classTypes: [
        { type: "Live Online", count: "24 sessions", iconName: "Wifi",   colorClass: "text-blue-600",    bgClass: "bg-blue-50",    borderClass: "border-blue-200"    },
        { type: "Offline",     count: "10 sessions", iconName: "MapPin", colorClass: "text-emerald-600", bgClass: "bg-emerald-50", borderClass: "border-emerald-200" },
        { type: "Recorded",    count: "55+ hrs",     iconName: "Play",   colorClass: "text-violet-600",  bgClass: "bg-violet-50",  borderClass: "border-violet-200"  },
        { type: "Masterclass", count: "5 batches",   iconName: "Award",  colorClass: "text-amber-600",   bgClass: "bg-amber-50",   borderClass: "border-amber-200"   },
      ],
    },
  },
];

export const fmt = (n) => n.toLocaleString("en-IN");
export const calcPct = (o, d) => Math.round(((o - d) / o) * 100);